name: Android CI # https://chat.openai.com/share/d004e660-2cea-4ac3-8831-1e384d6c71ac

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Add npm Global Bin to PATH
      run: echo 'export PATH=$PATH:$(npm bin -g)' >> $GITHUB_ENV

    - name: Install Firebase CLI
      run: |
        sudo npm install -g firebase-tools@latest
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Start Firebase Emulators
      run: |
        firebase emulators:start --only firestore,storage --export-on-exit=./emulator-export --debug &
  
    - name: Wait for Emulators to Start
      run: |
        sleep 10
        
    - name: Run Tests
      run: |
        ./gradlew test
        ./gradlew connectedAndroidTest com.example.DBAFirestoreTest

    # - name: Stop Firebase Emulators
    #   run: |
    #     firebase emulators:exec 'echo "action complete"'
